version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - app-network
    command: postgres -c listen_addresses='*'
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "5050:8080"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
    restart: always

  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: stock-service
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
